### ISSUE TITLE
the meaning of prob_move and prob_move2 in AIM

### ISSUE THREAD

**Issue by dyw2920** [8AquA8/Active_Ising_Model#1]
Very useful code! May I ask the physical meaning of prob_move = 2.0 * dt, and prob_move2 = 2.0 * prob_move in aim.py? I did not quite get it. Thank you!

**Comment by koesij** [comment]
I’m really glad to hear that you found the code useful!

prob_move determines the probability a particle will move horizontally (left or right) in the lattice within one time step.
The 2.0 factor accounts two possible horizontal directions.

prob_move2 determines the probability a particle will move vertically(up or down) within one time step. 
It builds on prob_move to ensure consistency for all four movement directions (left, right, up, down).

I hope this clarifies things. If you have any more questions, feel free to ask.

**Comment by dyw2920** [comment]
Thank you for your reply. So it is different from the original AIM, right? ( in which particle undergoes biased diffusion, with horizontal hop rate depending on the spin and epsilon).

**Comment by koesij** [comment]
prob_r incorporates the biased diffusion hopping mechanism. It calculates the likelihood of a particle moving to the right based on its spin and epsilon. If a random number is less than prob_r, the particle moves to the right; otherwise, it moves to the left. So it is the same with the original AIM.

**Comment by dyw2920** [comment]
Thanks
